In [29]:
import numpy as np

In [5]:
nodes = [1,2,3]
lines = [(1,2),(2,3)]

n = len(nodes)
m = len(lines)


_="""

 1 -------------> 2 -------------> 3

"""

In [54]:
def Cli(l,i):
    if any((i+1,ji+1)==lines[l] for ji in range(n)):
        return 1.0
    if any((ji+1,i+1)==lines[l] for ji in range(n)):
        return -1.0
    return 0.0


C = np.fromfunction(np.vectorize(Cli),(m,n),dtype=int)
C

array([[ 1., -1.,  0.],
       [ 0.,  1., -1.]])

In [55]:
beta = np.array([20.0, 1.0])

In [61]:
V = np.array([[9,7,6]]).T


In [66]:
Vdiff = C.dot(V)
print("Vdiff:\n",Vdiff)

I = np.diag(beta).dot(Vdiff)
print("I:\n",I)


Vdiff:
 [[2.]
 [1.]]
I:
 [[40.]
 [ 1.]]


In [72]:
i = 2

V*(-C.T.dot(I)).conj()

array([[-360.],
       [ 273.],
       [   6.]])

In [91]:
A = 2*np.random.rand(3,3)-1 + 2j * np.random.rand(3,3) - 1j
B = 2*np.random.rand(3,3)-1 + 2j * np.random.rand(3,3) - 1j
A

array([[ 0.80883163+0.29109241j,  0.96058418+0.95923363j,
         0.24564999+0.54751662j],
       [ 0.08725932-0.05983j   , -0.02161362-0.45564345j,
         0.03685463-0.50058923j],
       [ 0.83217534+0.761374j  , -0.27232623-0.46672988j,
        -0.50599703+0.34633861j]])

In [92]:
A.conj().dot(B.conj()) - (A.dot(B)).conj()

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])